nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.0.cjs

npmScopes:
  {
    shinoda-yosuke-lvgs:
      {
        npmPublishRegistry: "https://npm.pkg.github.com/",
        npmRegistryServer: "https://npm.pkg.github.com/",
        npmAlwaysAuth: true,
        npmAuthToken: "${GITHUB_TOKEN-}",
      },
  }
